<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="UpdateStore.aspx.cs" Inherits="UpdateStore" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3" CellSpacing="1" DataKeyNames="Serial" DataSourceID="SqlDataSource1s" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="Serial" HeaderText="Serial" InsertVisible="False" ReadOnly="True" SortExpression="Serial" />
            <asp:BoundField DataField="ArabicName" HeaderText="ArabicName" SortExpression="ArabicName" />
            <asp:BoundField DataField="EnglishName" HeaderText="EnglishName" SortExpression="EnglishName" />
            <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
            <asp:BoundField DataField="NumberOfLeans" HeaderText="NumberOfLeans" SortExpression="NumberOfLeans" />
            <asp:BoundField DataField="Phone1" HeaderText="Phone1" SortExpression="Phone1" />
            <asp:BoundField DataField="StoreKeeper" HeaderText="StoreKeeper" SortExpression="StoreKeeper" />
            <asp:BoundField DataField="AreaStock" HeaderText="AreaStock" SortExpression="AreaStock" />
        </Columns>
        <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
        <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
        <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
        <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
        <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#594B9C" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#33276A" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1s" runat="server" ConnectionString="<%$ ConnectionStrings:TopSoft %>" SelectCommand="SELECT [Serial], [ArabicName], [EnglishName], [Address], [NumberOfLeans], [Phone1], [StoreKeeper], [AreaStock] FROM [StoreCode]" UpdateCommand="Update StoreCode Set [ArabicName]=@ArabicName, [EnglishName]=@EnglishName, [Address]=@Address, [NumberOfLeans]=@NumberOfLeans, [Phone1]=@Phone1, [StoreKeeper]=@StoreKeeper, [AreaStock]=@AreaStock Where Serial=@Serial" DeleteCommand="Delete from StoreCode"></asp:SqlDataSource>
</asp:Content>

