<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="UpdateUnit.aspx.cs" Inherits="UpdateUnit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="Serial" DataSourceID="SqlDataSource1z" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="Serial" HeaderText="Serial" InsertVisible="False" ReadOnly="True" SortExpression="Serial" />
            <asp:BoundField DataField="ArabicName" HeaderText="ArabicName" SortExpression="ArabicName" />
            <asp:BoundField DataField="EnglishName" HeaderText="EnglishName" SortExpression="EnglishName" />
            <asp:BoundField DataField="DescName" HeaderText="DescName" SortExpression="DescName" />
            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
        </Columns>
        <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
        <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
        <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
        <RowStyle BackColor="White" ForeColor="#003399" />
        <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
        <SortedAscendingCellStyle BackColor="#EDF6F6" />
        <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
        <SortedDescendingCellStyle BackColor="#D6DFDF" />
        <SortedDescendingHeaderStyle BackColor="#002876" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1z" runat="server" ConnectionString="<%$ ConnectionStrings:TopSoft %>" SelectCommand="SELECT [Serial], [ArabicName], [EnglishName], [DescName], [Description] FROM [UnitCode]" UpdateCommand="Update UnitCode Set  [ArabicName]=@ArabicName, [EnglishName]=@EnglishName, [DescName]=@DescName, [Description]=@Description Where Serial=@Serial" DeleteCommand="Delete from Unitcode where serial=@serial"></asp:SqlDataSource>
</asp:Content>

